theme: jekyll-theme-hacker
title: [EazyTranscripts Installation Guide]
description: [A guide for installing and running EazyTranscripts on any machine that has docker installed.
Please be advised to install this application in your VPNs to improve the security of the system.]
